core/urls.py
from django.urls import path, include
from .views import *
from . import views
app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryDetailView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('process-payment', PaymentView.as_view(), name='process_payment')
]

dj-ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include("core.urls", namespace="core"))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

core/models.py
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from django_countries.fields import CountryField

'''
    1. Item added to cart
    2. Adding a billing address
    (Failed checkout)
    3. Payment
    (Preprocessing, processing, packaging etc.)
    4. Being delivered
    5. Received
'''

# Create your models here.
CATEGORY_CHOICES = (
    ('S', 'Shirt'),
    ('SW', 'Sport Wear'),
    ('O', 'Outwear')
)
LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)
ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    image = models.CharField(max_length=200, default=None, blank=True, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={"slug": self.slug})

    def add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={"slug": self.slug})

    def remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={"slug": self.slug})


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def __str__(self):
        return self.request.shipping_address

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block head_title %}{% endblock %}</title>
      {% block extra_head %}
      {% endblock %}
  
  <link rel="shortcut icon" href="../media/favicon.ico" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">  
  <link href={% static "css/bootstrap.min.css" %} rel="stylesheet">
  <link href={% static "css/style.css" %} rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header{
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header{
        height: 100vh;
      }
    }

  </style>
</head>

{% include "navbar.html" %}
  <body class="font ">  
  {% comment %} <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
  </div> {% endcomment %}
  {% if messages %}
    {% for message in messages %}
    <div class="modal" tabindex="-1" role="dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-body">
            <p>{{ message }}</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  {% endif %}
  {% block content  %}
  {% endblock content %}

  {% block extra_body %}
  {% endblock %} 

<!--   {% include "footer.html" %} -->

  {% block extra_scripts %}
  {% endblock extra_scripts %}

  <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

templates/checkout.html
{% extends "base.html" %}
{% load static %}
{% block content %}

  <main >
    <div class="container pt-5 ">
      <h2 class="my-5 h2 text-left">Checkout form</h2>
      <div class="row">
        <div class="col-md-8 mb-4">
          <div class="card">
            <form method="POST" class="card-body">
              {% csrf_token %}

              <h3>Shipping address</h3>

              <div class='hideable_shipping_form'>
                <div class="md-form mb-5">
                  <label for="shipping_address" class="">Address</label>
                  <input type='text'  id='shipping_address' name='shipping_address' class='form-control' />
                </div>
                <div class="md-form mb-5">
                  <label for="shipping_address2" class="">Address 2 (optional)</label>
                  <input type='text' id='shipping_address2' name='shipping_address2' class='form-control' />
                </div>
                <div class="row">
                  <div class="col-lg-4 col-md-12 mb-4">
                    <label for="country">Country</label>
                    {{ form.shipping_country }}
                    <div class="invalid-feedback">
                      Please select a valid country.
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 mb-4">
                    <label for="shipping_zip">Zip</label>
                    <input type='text' placeholder='Zip code' id='shipping_zip' name='shipping_zip' class='form-control' />
                    <div class="invalid-feedback">
                      Zip code required.
                    </div>
                  </div>
                </div>

                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="same_billing_address" id="same_billing_address">
                  <label class="custom-control-label" for="same_billing_address">Billing address is the same as my shipping address</label>
                </div>
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="set_default_shipping" id="set_default_shipping">
                  <label class="custom-control-label" for="set_default_shipping">Save as default shipping address</label>
                </div>

              </div>

              {% if default_shipping_address %}
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="use_default_shipping" id="use_default_shipping">
                <label class="custom-control-label" for="use_default_shipping">Use default shipping address: {{ default_shipping_address.street_address|truncatechars:10 }}</label>
              </div>
              {% endif %}

              <hr>

              <h3>Billing address</h3>

              <div class='hideable_billing_form'>
                <div class="md-form mb-5">
                  <label for="billing_address" class="">Address</label>
                  <input type='text'  id='billing_address' name='billing_address' class='form-control' />
                </div>

                <div class="md-form mb-5">
                  <label for="billing_address2" class="">Address 2 (optional)</label>
                  <input type='text' id='billing_address2' name='billing_address2' class='form-control' />
                </div>

                <div class="row">
                  <div class="col-lg-4 col-md-12 mb-4">
                    <label for="country">Country</label>
                    {{ form.billing_country }}
                    <div class="invalid-feedback">
                      Please select a valid country.
                    </div>
                  </div>

                  <div class="col-lg-4 col-md-6 mb-4">
                    <label for="billing_zip">Zip</label>
                    <input type='text' placeholder='Zip code' id='billing_zip' name='billing_zip' class='form-control' />
                    <div class="invalid-feedback">
                      Zip code required.
                    </div>
                  </div>

                </div>

                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="set_default_billing" id="set_default_billing">
                  <label class="custom-control-label" for="set_default_billing">Save as default billing address</label>
                </div>

              </div>

              {% if default_billing_address %}
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="use_default_billing" id="use_default_billing">
                <label class="custom-control-label" for="use_default_billing">Use default billing address: {{ default_billing_address.street_address|truncatechars:10 }}</label>
              </div>
              {% endif %}
              <hr>

              <h3>Payment option</h3>

              <div class="d-block my-3">
                {% for value, name in form.fields.payment_option.choices %}
                <div class="custom-control custom-radio">
                  <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
                </div>
                {%endfor%}
          
              </div>

              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

            </form>

          </div>

        </div> 
      </div>

    </div>
  </main>

{% endblock content %}

{% block extra_scripts %}
<script>
var hideable_shipping_form = $('.hideable_shipping_form');
var hideable_billing_form = $('.hideable_billing_form');

var use_default_shipping = document.querySelector("input[name=use_default_shipping]");
var use_default_billing = document.querySelector("input[name=use_default_billing]");

use_default_shipping.addEventListener('change', function() {
  if (this.checked) {
    hideable_shipping_form.hide();
  } else {
    hideable_shipping_form.show();
  }
})

use_default_billing.addEventListener('change', function() {
  if (this.checked) {
    hideable_billing_form.hide();
  } else {
    hideable_billing_form.show();
  }
})

</script>
{% endblock extra_scripts %}














templates/footer.html
<footer class="footer page-footer text-center font-small mt-2">

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-2 text-white">
      © 2022 Copyright:
    </div>
    <!--/.Copyright-->

  </footer>

templates/home.html
{% extends 'base.html' %}

{% block content %}
  <!--Main layout-->
  <main>
    <div class="m-0 h-800 d-flex justify-content-between bg-color">
      <img class="home-img" src="../media/img_2.png" alt="" height="700px" />
      <div class="container d-flex flex-column align-items-center">
        <img class="" src="../media/logo1.png" alt=""  height="100px" style="margin-top:200px;" />
        <div class=" text-white h3 text-center py-5 text-uppercase"><p class="center">STRIPE <p>CLOTHING<p> COLLECTION</p></div>
      </div>
      <div>
        <img class="home-img" src="../media/img.png" alt="" height="700px" />
      </div>
    </div>
    <div id="collection" class="container border my-4 p-4 border-dark rounded">
      <h3 class="py-3">BRAND NEW EXCLUSIVE COLLECTION</h3>

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        
        <div class="row">

          {% for item in object_list %}
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-3">

            <!--Card-->
            <div class="card border-dark" >

              <!--Card image-->
              <div class="view overlay">
                <a href="{{ item.get_absolute_url }}">
                  <img src="{{item.image}}" class="card-img-top" height="250px" width="450px" alt="">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="text-secondary text-decoration-none">
                  <h6>{{item.get_category_display}}</h6>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="text-dark text-decoration-none text-uppercase">{{ item.title }}
                      {% comment %} <span class="badge {{ item.get_label_display }}-color">NEW</span> {% endcomment %}
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>${{item.price}}</strong>
                </h4>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
          <!--Grid column-->
          {% endfor %}
        </div>
        
      </section>
      <!--Pagination-->

      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          <!--Arrow left-->
          {% if page_obj.has_previous %}
            <li class="page-item ">
              <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
              </a>
            </li>
          {%endif%}
          <li class="page-item active">
            <a class="page-link" href="?page={{page_obj.number}}">{{page_obj.number}}
              <span class="sr-only">(current)</span>
            </a>
          </li>
          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}
      <!--Pagination-->

    </div>
    
  </main>

{% endblock content %}

templates/navbar.html
{% load cart_template_tags %}

<!-- Navbar -->
<nav class="navbar scrolled navbar-expand-lg navbar-dark fixed-top navbar-color" >
      <!-- Brand -->
      <a class="navbar-brand" href="/">
        <img src="../media/logo_initial.png" alt=""  height="30px"/>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mt-2 mt-lg-0  mr-auto">
          <li class="nav-item active">
            <a class="nav-link " href="/">HOME
              <span class="sr-only">(current)</span>    
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="#collection"
              >COLLECTION</a>
          </li>
        </ul>

        <!-- Right -->
        <ul class="navbar-nav  mr-sm-2">
          {% if request.user.is_authenticated %}
          <li class="nav-item badge btn-outline-primary my-1 ">
            <a href="{% url 'core:order-summary'%}" class="nav-link ">
              <span class=" my-sm-0 z-depth-1 mr-1"> {{ request.user|cart_item_count }}</span>
              <i class="fas fa-shopping-cart"></i>
              <span class=" d-none d-sm-inline-block"> CART </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_logout' %}">
              <span class="d-none d-sm-inline-block"> LOGOUT </span>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link " href="{% url 'account_signup' %}">
              <span class="d-none d-sm-inline-block"> SIGNUP </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url 'account_login' %}">
              <span class="d-none d-sm-inline-block"> LOGIN </span>
            </a>
          </li>
          {% endif %}
        </ul>
      </div>

  </nav>
  <!-- Navbar -->

templates/order_summary.html
{% extends "base.html" %}

{% block content %}
  <main>
    <div class="container pt-5 border border-dark" style="margin-top:5rem;">
        <div class="table-responsive text-nowrap">
        <h2>Order Summary</h2>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Item title</th>
                <th scope="col">Price</th>
                <th scope="col">Quantity</th>
                <th scope="col">Total Item Price</th>
            </tr>
            </thead>
            <tbody>
            {% for order_item in object.items.all %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ order_item.item.title }}</td>
                <td>{{ order_item.item.price }}</td>
                <td>
                    <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}">
                        <i class="fa fas fa-minus mr-2"></i></a> 
                    {{ order_item.quantity }}
                    <a href="{% url 'core:add-to-cart' order_item.item.slug %}">
                        <i class="fas fa-plus ml-2"></i></a>
                </td>
                <td>
                {% if order_item.item.discount_price %}
                    ${{ order_item.get_total_discount_item_price }}
                    <span class="badge badge-primary">Saving ${{ order_item.get_amount_saved }}</span>
                {% else %}
                    ${{ order_item.get_total_item_price }}
                {% endif %}
                <a style='color: red;' href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                    <i class="fas fa-trash float-right"></i>
                </a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan='5'>Your cart is empty</td>
            </tr>
            <tr>
                <td colspan="5">
                <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
                </td>
            </tr>
            {% endfor %}
            {% if object.get_total %}
            <tr>
                <td colspan="4"><b>Order Total</b></td>
                <td><b>${{ object.get_total }}</b></td>
            </tr>
            <tr>
                <td colspan="5">
                <a class='btn btn-warning float-right ml-2' href='/checkout/'>Proceed to checkout</a>
                <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
                </td>
            </tr>
            {% endif %}
            </tbody>
        </table>

        </div>

    </div>
  </main>

{% endblock content %}

templates/process_payment.html
{% extends "base.html" %}
{% block title %}Make Payment{% endblock %}

{% block content %}
    <h4 class="pt-5 mt-3 text-center">Pay with PayPal</h4>
    <!-- Set up a container element for the button -->
    <div id="paypal-button-container" class="pt-5 text-center"></div>

    <!-- Include the PayPal JavaScript SDK -->
    <script src="https://www.paypal.com/sdk/js?client-id=AStcCqWg-VolQTBHyLRY_4BCI11HTc1df8GCE9rRRJoI_WCmgYErJ4PwLdsYM4LsXYQkilTMZno4dzBX&currency=USD&disable-funding=credit"></script>

    <script>

        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: '{{ object.get_total }}'
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(orderData) {
                    // Successful capture! For demo purposes:
                    console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
                    var transaction = orderData.purchase_units[0].payments.captures[0];
                    //alert('Transaction '+ transaction.status + ': ' + transaction.id + '\n\nSee console for all available details');
                    // Replace the above to show a success message within this page, e.g.
                    const element = document.getElementById('paypal-button-container');
                    element.innerHTML = '';
                    element.innerHTML = '<h3 class="pt-5 mt-3 text-center">Thank you for your payment!</h3>';
                    //actions.redirect('payment_done');
                });
            }


        }).render('#paypal-button-container');
    </script>
{% endblock %}

templates/product.html
{% extends 'base.html' %}
{% block content %}
  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-6 mb-4">
          <img src="{{ object.image }}" class="img-fluid" alt=""/>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
              </a>
            </div>
            <h4>{{ object.title }}</h4>

            <p class="lead">
              {% if object.discount_price %}
              <span class="mr-1">
                <del>${{ object.price }}</del>
              </span>
              <span>${{ object.discount_price }}</span>
              {% else %}
              <span>${{ object.price }}</span>
              {% endif %}
            </p>

            <p class="lead font-weight-bold">{{ object.description}}</p>
            {% comment %} <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> {% endcomment %}
            <a href={{ object.add_to_cart_url }} class="btn btn-primary btn-md my-0 p" >
              Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <a href={{ object.remove_from_cart_url }} class="btn btn-danger btn-md my-0 p" >
              Remove from cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->
    </div>
  </main>

{% endblock content %}